# Generated by Django 5.2.5 on 2025-11-14 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
